package com.centling.radio.utils;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;

public class PropertyUtils {

	private static Properties properties = new Properties();

	private static String path = PropertyUtils.class.getClassLoader().getResource("config.properties").getPath();
//	private static String path = "/etc/cet22-radio/config.properties";

	static {
		try {
			InputStream is = PropertyUtils.class.getClassLoader().getResourceAsStream("config.properties");
			properties.load(is);
			is.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public static Properties getProperties() {
		return properties;
	}

	public static String getProperty(String key) {
		return properties.getProperty(key);
	}

	public static void modifyProperty(String key, String value) throws Exception {
		if(properties.containsKey(key)) {
			properties.setProperty(key, value);
			OutputStream os = new FileOutputStream(path);
			properties.store(os, "Auto Generated by System");
			os.close();
		} else {
			throw new Exception("The key = " + key + " doesn't exist");
		}
		
	}
}
